name: WisperKbd
options:
  bundleIdPrefix: com.tomasen
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"

targets:
  WisperKbd:
    type: application
    platform: macOS
    sources:
      - WisperKbd
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.tomasen.inputmethod.WisperKbd
        INFOPLIST_FILE: WisperKbd/Info.plist
        CODE_SIGN_ENTITLEMENTS: WisperKbd/WisperKbd.entitlements
        GENERATE_INFOPLIST_FILE: false
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_HARDENED_RUNTIME: true
    dependencies:
      - package: WhisperKit
